host: # Address/domain name where the server is listening
port: 8000 # Port where the server is listening
db:
  host: # Database host
  port: 5432 # Database port
  user: # Database user
  password: # Database password
  database: # Database name
  enable_ssl: false # Use SSL to connect to the database
ssl:
  enabled: true # Enable SSL for the server
  cert_file: gotodo.crt # Path to SSL certificate file
  key_file: gotodo.key # Path to SSL key file
jwt:
  lifespan:
    access_token: 30 # Lifespan of access token in minutes
    refresh_token: 43200 # Lifespan of refresh token in minutes (30 days)
  secrets:
    access: # Secret for signing access tokens
    refresh: # Secret for signing refresh tokens
