// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (id, user_id, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, description, created_at, updated_at
`

type CreateListParams struct {
	ID          string      `json:"id"`
	UserID      string      `json:"user_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :execrows
DELETE FROM lists
WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteList, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteListByIdWithUserId = `-- name: DeleteListByIdWithUserId :exec
DELETE FROM lists
WHERE id = $1 AND user_id = $2
`

type DeleteListByIdWithUserIdParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteListByIdWithUserId(ctx context.Context, arg DeleteListByIdWithUserIdParams) error {
	_, err := q.db.Exec(ctx, deleteListByIdWithUserId, arg.ID, arg.UserID)
	return err
}

const getList = `-- name: GetList :one
SELECT id, user_id, title, description, created_at, updated_at FROM lists
WHERE id = $1
`

func (q *Queries) GetList(ctx context.Context, id string) (List, error) {
	row := q.db.QueryRow(ctx, getList, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListIdsAccessible = `-- name: GetListIdsAccessible :many
SELECT id FROM lists l
WHERE l.user_id = $1 OR id IN (
    SELECT list_id FROM list_shares ls WHERE ls.user_id = $1
)
`

func (q *Queries) GetListIdsAccessible(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getListIdsAccessible, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLists = `-- name: GetLists :many
SELECT id, user_id, title, description, created_at, updated_at FROM lists
`

func (q *Queries) GetLists(ctx context.Context) ([]List, error) {
	rows, err := q.db.Query(ctx, getLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsAccessibleByUserId = `-- name: GetListsAccessibleByUserId :many
SELECT l.id, l.user_id, l.title, l.description, l.created_at, l.updated_at FROM lists l
WHERE l.user_id = $1 OR l.id IN (
    SELECT ls.list_id FROM list_shares ls WHERE ls.user_id = $1
)
`

func (q *Queries) GetListsAccessibleByUserId(ctx context.Context, userID string) ([]List, error) {
	rows, err := q.db.Query(ctx, getListsAccessibleByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsByOwnerId = `-- name: GetListsByOwnerId :many
SELECT id, user_id, title, description, created_at, updated_at FROM lists
WHERE user_id = $1
`

func (q *Queries) GetListsByOwnerId(ctx context.Context, userID string) ([]List, error) {
	rows, err := q.db.Query(ctx, getListsByOwnerId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsBySharedUserId = `-- name: GetListsBySharedUserId :many
SELECT l.id, l.user_id, l.title, l.description, l.created_at, l.updated_at FROM lists l
JOIN list_shares ls ON l.id = ls.list_id
WHERE ls.user_id = $1
`

func (q *Queries) GetListsBySharedUserId(ctx context.Context, userID string) ([]List, error) {
	rows, err := q.db.Query(ctx, getListsBySharedUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateList = `-- name: UpdateList :one
UPDATE lists
SET title = $1, description = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, user_id, title, description, created_at, updated_at
`

type UpdateListParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	ID          string      `json:"id"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (List, error) {
	row := q.db.QueryRow(ctx, updateList, arg.Title, arg.Description, arg.ID)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
