// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share.sql

package db

import (
	"context"
)

const createShare = `-- name: CreateShare :one
INSERT INTO list_shares (list_id, user_id)
VALUES ($1, $2)
RETURNING list_id, user_id
`

type CreateShareParams struct {
	ListID string `json:"list_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (ListShare, error) {
	row := q.db.QueryRow(ctx, createShare, arg.ListID, arg.UserID)
	var i ListShare
	err := row.Scan(&i.ListID, &i.UserID)
	return i, err
}

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM list_shares
WHERE list_id = $1 AND user_id = $2
`

type DeleteShareParams struct {
	ListID string `json:"list_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteShare(ctx context.Context, arg DeleteShareParams) error {
	_, err := q.db.Exec(ctx, deleteShare, arg.ListID, arg.UserID)
	return err
}

const readShares = `-- name: ReadShares :many
SELECT ls.list_id, ls.user_id, u.username FROM list_shares ls
JOIN users u ON ls.user_id = u.id
WHERE ls.list_id = $1
`

type ReadSharesRow struct {
	ListID   string `json:"list_id"`
	UserID   string `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) ReadShares(ctx context.Context, listID string) ([]ReadSharesRow, error) {
	rows, err := q.db.Query(ctx, readShares, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadSharesRow{}
	for rows.Next() {
		var i ReadSharesRow
		if err := rows.Scan(&i.ListID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
