// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share.sql

package db

import (
	"context"
)

const createShare = `-- name: CreateShare :one
INSERT INTO list_shares (list_id, user_id)
VALUES ($1, $2)
RETURNING list_id, user_id
`

type CreateShareParams struct {
	ListID string `json:"list_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (ListShare, error) {
	row := q.db.QueryRow(ctx, createShare, arg.ListID, arg.UserID)
	var i ListShare
	err := row.Scan(&i.ListID, &i.UserID)
	return i, err
}
