// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, list_id, user_id, parent_id, title, description, complete_before)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, parent_id, list_id, user_id, title, description, completed, created_at, updated_at, complete_before, completed_at
`

type CreateTodoParams struct {
	ID             string           `json:"id"`
	ListID         string           `json:"list_id"`
	UserID         string           `json:"user_id"`
	ParentID       pgtype.Text      `json:"parent_id"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	CompleteBefore pgtype.Timestamp `json:"complete_before"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.ID,
		arg.ListID,
		arg.UserID,
		arg.ParentID,
		arg.Title,
		arg.Description,
		arg.CompleteBefore,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ListID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompleteBefore,
		&i.CompletedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const deleteTodoByIdWithListId = `-- name: DeleteTodoByIdWithListId :exec
DELETE FROM todos
WHERE id = $1 AND list_id = $2
`

type DeleteTodoByIdWithListIdParams struct {
	ID     string `json:"id"`
	ListID string `json:"list_id"`
}

func (q *Queries) DeleteTodoByIdWithListId(ctx context.Context, arg DeleteTodoByIdWithListIdParams) error {
	_, err := q.db.Exec(ctx, deleteTodoByIdWithListId, arg.ID, arg.ListID)
	return err
}

const getTodoByIdWithListId = `-- name: GetTodoByIdWithListId :one
SELECT id, parent_id, list_id, user_id, title, description, completed, created_at, updated_at, complete_before, completed_at FROM todos
WHERE id = $1 AND list_id = $2
`

type GetTodoByIdWithListIdParams struct {
	ID     string `json:"id"`
	ListID string `json:"list_id"`
}

func (q *Queries) GetTodoByIdWithListId(ctx context.Context, arg GetTodoByIdWithListIdParams) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByIdWithListId, arg.ID, arg.ListID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ListID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompleteBefore,
		&i.CompletedAt,
	)
	return i, err
}

const getTodosAccessibleByUserId = `-- name: GetTodosAccessibleByUserId :many
SELECT t.id, t.parent_id, t.list_id, t.user_id, t.title, t.description, t.completed, t.created_at, t.updated_at, t.complete_before, t.completed_at FROM todos t
JOIN lists l ON t.list_id = l.id
WHERE l.user_id = $1 OR l.id IN (
    SELECT ls.list_id FROM list_shares ls WHERE ls.user_id = $1
)
`

func (q *Queries) GetTodosAccessibleByUserId(ctx context.Context, userID string) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodosAccessibleByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ListID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompleteBefore,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByList = `-- name: GetTodosByList :many
SELECT id, parent_id, list_id, user_id, title, description, completed, created_at, updated_at, complete_before, completed_at FROM todos
WHERE list_id = $1
`

func (q *Queries) GetTodosByList(ctx context.Context, listID string) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodosByList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ListID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompleteBefore,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByListIds = `-- name: GetTodosByListIds :many
SELECT id, parent_id, list_id, user_id, title, description, completed, created_at, updated_at, complete_before, completed_at FROM todos
WHERE list_id = ANY($1::text[])
`

func (q *Queries) GetTodosByListIds(ctx context.Context, dollar_1 []string) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodosByListIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ListID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompleteBefore,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $1, description = $2, completed = $3, complete_before = $4, updated_at = CURRENT_TIMESTAMP, completed_at = CASE WHEN $3 THEN CURRENT_TIMESTAMP ELSE NULL END
WHERE id = $5
RETURNING id, parent_id, list_id, user_id, title, description, completed, created_at, updated_at, complete_before, completed_at
`

type UpdateTodoParams struct {
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	Completed      bool             `json:"completed"`
	CompleteBefore pgtype.Timestamp `json:"complete_before"`
	ID             string           `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.CompleteBefore,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ListID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompleteBefore,
		&i.CompletedAt,
	)
	return i, err
}
