name: Deploy

on:
  workflow_run:
    workflows: [Build and Release]
    types: [completed]
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: Ben-PP/action-publy-publish@v1.0.0
        with:
          publy-url: https://publy.bendevs.com
          pub: go-todo
          api-token: ${{secrets.PUBLY_TOKEN}}
